# This is a basic workflow to help you get started with Actions

name: pipeline
# Controls when the action will run.
on:
# Triggers the workflow on push or pull request events but onlythe main branch
  push:
    branches: [ main ]
    paths:
    - Chapter15/**
    - .github/workflows/pipeline.yaml
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  ACRNAME: handsonakspipeline
